package com.eleven.group.myrecipiebook.activity;

import com.eleven.group.myrecipiebook.R;

public class RecipesMeals {
    public static String[] names1 = new String[]{"Buddha     Bowl","Cashew Chicken","Soy        Salmon","Pasta", "Garlic     Shrimp", "Mustard chicken","Sweet sour pork", "Lime chicken"};
    public static int[] resourceIds1 = new int[]{R.drawable.buddhabowl, R.drawable.cashewchicken, R.drawable.honeysoysalmon,
            R.drawable.pasta, R.drawable.honeygarlicshrimp, R.drawable.honeymustardchicken, R.drawable.sweetsourpork, R.drawable.limechicken};

    public static String[] ingredients = new String[]{
            "1 tablespoon oil`16 oz chickpea, 1 can, drained and rinsed`1 teaspoon salt`1 teaspoon cumin`½ teaspoon garlic powder`½ teaspoon tumeric`1 teaspoon red pepper flake`2 sweet potato`oil, to taste`salt, to taste`pepper`1 cup quinoa, cooked`1 cup mixed green`½ avocado, sliced`1 tablespoon pumpkin seed `sliced tofu",
            "1 cup all-purpose flour`1 tsp baking powder`dash of salt`1 tbsp sugar`1 egg`1 cup milk`2 tbsp cooking oil",
            "2 cups all-purpose flour`1/3 cup sugar`1 tsp baking powder`1/4 tsp baking soda`dash of salt`1/2 cup unsalted butter, frozen`1/2 cup raisins`1/2 cup sour cream`1 large egg`additional 1 tsp sugar",
            "1 loaf of thick sliced bread`6 large eggs`1/4 cup buttermilk`1/2 tsp vanilla extract`dash of cinnamon",
            "1/2 cup butter`1/2 cup sugar`2 large eggs`3/4 cup applesauce`1 3/4 cup flour`1 tbsp baking powder`dash of salt`1/4 cup melted butter`1/4 tsp cinnamon`additional 1/4 cup sugar",
            "1 1/2 cup all-purpose flour`1/4 cup sugar`1/4 cup cornstarch`2 tsp baking powder`1/2 teaspoon baking soda`dash of salt`1 1/4 cups buttermilk`2 large eggs`1/2 cup unsalted melted butter (cooled)`1 tsp vanilla extract ",
            "1 slice of bread`1 toaster",
            "2 cups all-purpose flour`1 tsp baking soda`dash of salt`1 cup sugar`1/4 cup salted butter`2 large eggs`3 mashed bananas`1 cup plain or vanilla greek yogurt`1 tsp vanilla extract"
    };
    public static String[] directions = new String[]{
            "Preheat oven to 450°F (230°C)`Heat olive oil in a skillet over medium heat. `Add chickpeas, salt, pepper, cumin, garlic powder, turmeric, and chili flakes, and stir until toasted.` Remove from pan. `Heat sesame oil in a skillet over medium heat. `Add tofu, and sprinkle with ginger powder, garlic powder, salt, and pepper. `Sear until a golden crust forms, then flip and do the same for the other side. Set aside.`On a baking sheet, toss sweet potatoes and broccoli in oil, salt, and pepper.`Bake for 30 minutes.`In a bowl, combine ingredients for each sauce.`Divide into 4 small tupperware containers.`To build the bowls, fill four tupperwares half with quinoa, half with brown rice.`Layer the ingredients of each bowl on top`Heat a pan over medium-low heat`In a bowl, mix together the dry ingredients. In another bowl mix together the wet ingredients. Add wet ingredients to dry ingredients; the batter should be lumpy.`Scoop batter onto pan, and flip when you see bubbles.`Flip and cook the other side. Serve hot.",
            "Preheat oven to 400 degrees.`In a bowl, mix flour, 1/3 cup sugar, baking powder, baking soda, and salt. Grate butter into flour mixture and use your fingers to work in butter, mixture should be coarse.`Stir in raisins.`In another bowl, whisk sour cream and egg.`Add sour cream mixture to flour mixture until large dough clumps form. Shape the dough into a ball.`Place on a lightly floured surface and pat into a 7 inch circle roughly 3/4-inch thick. Sprinkle with additional 1 tsp sugar. Cut dough into 8 triangles; place on a cookie sheet lined with parchment paper. Bake until golden brown, about 15 to 17 minutes. Let cool for 5 minutes and serve warm or at room temperature.",
            "Heat pan over medium high heat.`Combine all ingredients in a bowl wide enough to dip bread in.`Dip in one slice of bread in the mixture and flip to coat the other side.`Place bread in pan and flip once browned, usually about a minute.`Repeat for remaining slices.",
            "Preheat oven to 425 and grease muffin pan (12 muffins).`Cream butter and sugar.`Add eggs and applesauce.`In another bowl combine flour, baking powder, and salt.`Add the dry mixture to the wet and stir to combine.`Spoon batter into the muffin pan, filling to the top.`Bake for 15 minutes or until done.`Remove muffins from pan immediately and dip muffin tops in 1/4 cup melted butter. Combine additional 1/4 cup sugar and cinnamon. Sprinkle onto the tops of muffins.",
            "Heat waffle maker.`In a bowl mix together the dry ingredients.`In another bowl mix together the wet ingredients. `Add the wet ingredients to dry ingredients.`Grease waffle maker and pour 1 cup or 1/2 cup of batter into waffle maker, depending on if it is large or small.`Cook under golden brown and serve hot.",
            "Place slice of bread into toaster.`Gently depress the lever on the starboard side of the toaster to initiate the heating mechanism.`After ~3 minutes the bread, now toast, will be forcefully ejected from the top of the toaster. This is normal and not cause for alarm.`Remove the finished toast from the toaster and enjoy with your favorite fruit based spread!",
            "Preheat oven to 350 degrees and grease two loaf pans.`Combine flour, baking soda, and salt.`In another bowl cream the butter and sugar and add the eggs, banana, yogurt, and vanilla.`Add the wet ingredients to the dry ingredients.`Pour batter into the loaf pans.`Bake for 1 hour or until done.`Let cool for 10-15 minutes and then remove from pan. Serve once cooled."
    };
} // Recipes