package com.eleven.group.myrecipiebook.activity;

import com.eleven.group.myrecipiebook.R;

public class RecipesMeals {
    public static String[] names1 = new String[]{"Buddha Bowl","Cashew Chicken","Soy Salmon","Pasta", "Garlic Shrimp", "Mustard chicken","Sweet sour pork", "Lime chicken"};
    public static int[] resourceIds1 = new int[]{R.drawable.buddhabowl, R.drawable.cashewchicken, R.drawable.honeysoysalmon,
            R.drawable.pasta, R.drawable.honeygarlicshrimp, R.drawable.honeymustardchicken, R.drawable.sweetsourpork, R.drawable.limechicken};

    public static String[] ingredients = new String[]{
            "1 tablespoon oil`16 oz chickpea, 1 can, drained and rinsed`1 teaspoon salt`1 teaspoon cumin`½ teaspoon garlic powder`½ teaspoon tumeric`1 teaspoon red pepper flake`2 sweet potato`oil, to taste`salt, to taste`pepper`1 cup quinoa, cooked`1 cup mixed green`½ avocado, sliced`1 tablespoon pumpkin seed `sliced tofu",
            "6 tablespoons soy sauce`1 tablespoon hoisin sauce`1 tablespoon rice vinegar`2 tablespoons honey`1 teaspoon sesame oil`½ tablespoon ginger, minced`2 cloves garlic, minced`¾ lb chicken breast, cut into 1-inch (2 1/2 cm) pieces`salt, to taste`pepper, to taste\n`1 tablespoon cornstarch`1 tablespoon sesame oil`4 cups broccoli floret`1 red bell pepper, cut into 1-inch (2 1/2 cm) pieces`¾ cup raw cashew`½ cup water`brown rice, to serve",
            "12 oz skinless salmon`1 tablespoon olive oil`4 cloves garlic, minced`2 teaspoons ginger, minced`½ teaspoon red pepper`1 tablespoon olive oil`⅓ cup less sodium soy sauce`⅓ cup honey",
            "4 tablespoons olive oil, divided`1 lb chicken breast, diced`2 carrot, sliced`1 zucchini, sliced`1 yellow squash, sliced`4 cups kale, chopped`2 cloves garlic, minced`3 cups whole grain whole wheat rotini pasta`cooked al dente according to package instructions`2 teaspoons oregano, divided`2 teaspoons salt, divided`2 teaspoons pepper, divided",
            "1 lb raw shrimp`1 ½ tablespoons garlic, minced`2 teaspoons ginger, minced`½ teaspoon crushed red pepper`1 tablespoon olive oil`⅓ cup honey`⅓ cup soy sauce `scallion, thinly sliced",
            "⅓ cup honey`¼ cup dijon mustard`2 tablespoons olive oil`2 cloves garlic, minced`2 teaspoons salt`1 teaspoon pepper`4 boneless, skinless chicken thigh`¼ cup bacon, chopped`4 cups romaine lettuce, chopped`1 cup cherry tomatoes, halved`¼ red onion, sliced`1 avocado, pitted and sliced",
            "2 lb pork shoulder, or pork butt`2 cloves garlic, minced`1 teaspoon black pepper`¼ cup green onion`¼ cup soy sauce`3 egg, beaten`1 ½ cups cornstarch`1 tablespoon vegetable oil`1 red bell pepper`1 green bell pepper`1 white onion, cut into wedges`8 oz chopped pineapple with syrup`¼ cup vinegar`¼ cup soy sauce`¼ cup ketchup`¼ cup sugar",
            "oil, of your preference, to taste`1 lb boneless, skinless chicken breast, cubed`salt, to taste`pepper, to taste`1 lime, juiced`⅓ cup fresh cilantro, minced`1 red bell pepper, diced`½ red onion, diced`2 cloves garlic, minced`1 bag riced cauliflower`1 cup corn, steamed`½ teaspoon chili powder, optional`1 can black bean, rinsed and drained, optional`lime, cut into wedges, optional"
    };
    public static String[] directions = new String[]{
            "Preheat oven to 450°F (230°C)`Heat olive oil in a skillet over medium heat. `Add chickpeas, salt, pepper, cumin, garlic powder, turmeric, and chili flakes, and stir until toasted.` Remove from pan. `Heat sesame oil in a skillet over medium heat. `Add tofu, and sprinkle with ginger powder, garlic powder, salt, and pepper. `Sear until a golden crust forms, then flip and do the same for the other side. Set aside.`On a baking sheet, toss sweet potatoes and broccoli in oil, salt, and pepper.`Bake for 30 minutes.`In a bowl, combine ingredients for each sauce.`Divide into 4 small tupperware containers.`To build the bowls, fill four tupperwares half with quinoa, half with brown rice.`Layer the ingredients of each bowl on top`Heat a pan over medium-low heat`In a bowl, mix together the dry ingredients. In another bowl mix together the wet ingredients. Add wet ingredients to dry ingredients; the batter should be lumpy.`Scoop batter onto pan, and flip when you see bubbles.`Flip and cook the other side. Serve hot.",
            "In a medium bowl, combine the soy sauce, hoisin sauce, rice vinegar, honey, sesame oil, ginger, and garlic. Set aside.`In a medium bowl, season the chicken with salt, pepper, and cornstarch.`Heat a fry pan over medium-high heat and add sesame oil. `Add the chicken and cook for 5-6 minutes, or until the chicken begins to brown.`Remove chicken and set aside in a separate bowl.`Add the broccoli and bell peppers, and cook for 2-3 minutes.`Add the chicken, cashews and sauce. Stir together and allow sauce to thicken.`Remove from heat and serve over brown rice.`Heat pan over medium high heat.`Combine all ingredients in a bowl wide enough to dip bread in.`Dip in one slice of bread in the mixture and flip to coat the other side.`Place bread in pan and flip once browned, usually about a minute.`Repeat for remaining slices.",
            "Place salmon in a sealable bag or medium bowl.`In a small bowl or measuring cup, mix marinade ingredients.`Pour half of the marinade on the salmon. Save the other half for later.`Let the salmon marinate in the refrigerator for at least 30 minutes.`In a medium pan, heat oil. Add salmon to the pan, but discard the used marinade. `Cook salmon on one side for about 2-3 minutes, then flip over and cook for an additional 1-2 minutes.`Remove salmon from pan. Pour in remaining marinade and reduce.`Serve the salmon with sauce and a side of veggies. We used broccoli.",
            "Heat a large skillet with 2 tablespoons of olive oil on medium-high heat.`Add in diced chicken breast, followed by 1 teaspoon salt, 1 teaspoon pepper, and 1 teaspoon oregano. Cook until no longer pink. `Remove chicken from skillet and set aside.`Add carrots to skillet and sauté for 2-3 minutes until tender.`Add in zucchini and yellow squash, and sauté for an additional minute until they become slightly translucent.`Put kale, followed by 2 tablespoons olive oil, 1 teaspoon salt, and 1 teaspoon pepper. `Sauté until kale begins to wilt.`Move veggies aside with spatula and add in garlic. `Sauté for about 30 seconds and then combine with the veggies. (This works best if you add garlic to the center of the skillet where there is more heat.)`Add in the cooked rotini pasta and chicken, followed by 1 teaspoon oregano and mix until evenly incorporated. `Remove skillet from heat.`If using plastic tupperware for your weekday meal prep, allow pasta to cool for about 10 minutes before filling the containers. `Refrigerate up to 4 days.Or serve immediately for a family dinner. ",
            "Place shrimp in a sealable bag or medium bowl`In a small bowl or measuring cup, mix marinade ingredients.`Pour half of the marinade on the shrimp. Save the other half for later.`Let the shrimp marinate in the refrigerator for at least 15 minutes.`In a medium pan, heat oil. Add shrimp to the pan, but discard the used marinade. Cook shrimp on one side for about a minute, then flip over.`Pour in remaining marinade and cook until shrimp is cooked through and just firm. Remove the shrimp from the pan and let the marinade reduce.`Serve the shrimp with sauce and garnish with green onion.",
            "In a small bowl or liquid measuring cup, mix the honey, mustard, oil, garlic, salt and pepper.`Place the chicken thighs in a dish and pour the marinade over the chicken, reserving half for later.`Flip the chicken thighs over, fully covering them in the marinade.`Cover the dish with plastic wrap and refrigerate for 30 minutes to an hour.`Heat a large skillet over medium heat and place the chicken thighs in the pan. `Cook for five minutes on each side, or until the chicken is cooked through.`Remove the chicken and set aside.`Wipe the pan clean and place back on the heat.`Add the chopped bacon to the pan and cook until crispy, about ten minutes.`Transfer the bacon to a paper towel-lined plate to drain.`Add three tablespoons of water to the reserved marinade and stir to combine.`Slice the chicken into strips.`Add the romaine, cherry tomatoes, red onion, avocado, cooked bacon, and chicken to a bowl and drizzle with the remaining honey mustard dressing.",
            "Cut pork into bite-sized pieces and place in a medium-sized bowl.`Season with pepper and add soy sauce, garlic, and green onion.`Cover and let marinate for 1-2 hours.`Coat pork pieces with egg, dip in cornstarch, and fry until crispy and golden (about 2 minutes).`Drain on paper towels.`Heat 1 tablespoon of vegetable oil in a skillet over medium-high heat. Add the onion and bell pepper.`Once the vegetables start to become tender, add pineapple with syrup.`Stir for 30 seconds before adding vinegar, soy sauce, ketchup, and sugar. Stir regularly over medium-high heat for 3-4 minutes as water evaporates and sauce thickens.`Add the pork to the pan once the sauce begins to thicken. Stir to coat evenly.`Garnish with additional green onions and a sprinkle of sesame seeds.",
            "Heat preferred cooking oil in a large skillet over medium-high heat. `Add chicken, season with salt and pepper, and cook until cooked through and no longer pink.`Add lime juice and cilantro. Stir to combine. Remove chicken from pan, place on a plate, and set aside.`Add a little more oil to pan if needed, then add red onion, bell pepper, and garlic. Stir to combine. Allow to cook until onion begins to turn transparent, stirring occasionally.`Add riced cauliflower, corn, and chili powder. Cook until cauliflower is soft and remove from heat.`Distribute black beans, chicken, and cauliflower mixture evenly between 4 containers. Top with a wedge of lime.`This meal prep can be refrigerated for up to 4 days."
        };
} // Recipes